import React, { useState, useEffect } from 'react';
import { Play, Plus, Trash2, Save, Download, AlertTriangle, CheckCircle, XCircle, ChevronDown, ChevronUp, Activity } from 'lucide-react';

export default function ManualTestTab() {
  const [method, setMethod] = useState('GET');
  const [url, setUrl] = useState('');
  const [headers, setHeaders] = useState([{ key: '', value: '' }]);
  const [body, setBody] = useState('');
  const [assertions, setAssertions] = useState([{ type: 'status', expected: '200' }]);
  
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState(null);
  const [errorMsg, setErrorMsg] = useState('');
  
  const [savedTests, setSavedTests] = useState([]);
  const [showSaved, setShowSaved] = useState(false);

  useEffect(() => {
    const saved = localStorage.getItem('api_tester_saved_tests');
    if (saved) {
      setSavedTests(JSON.parse(saved));
    }
  }, []);

  const saveTestCase = () => {
    if (!url) return alert('Please enter a URL first.');
    const testCase = {
      id: Date.now(),
      name: `${method} ${url.split('?')[0].substring(0, 30)}...`,
      method,
      url,
      headers: headers.filter(h => h.key && h.value),
      body,
      assertions: assertions.filter(a => a.type && a.expected)
    };
    const updated = [...savedTests, testCase];
    setSavedTests(updated);
    localStorage.setItem('api_tester_saved_tests', JSON.stringify(updated));
    alert('Test case saved successfully!');
  };

  const loadTestCase = (tc) => {
    setMethod(tc.method);
    setUrl(tc.url);
    setHeaders(tc.headers.length ? tc.headers : [{ key: '', value: '' }]);
    setBody(tc.body || '');
    setAssertions(tc.assertions.length ? tc.assertions : [{ type: 'status', expected: '200' }]);
    setShowSaved(false);
  };

  const deleteTestCase = (id) => {
    const updated = savedTests.filter(t => t.id !== id);
    setSavedTests(updated);
    localStorage.setItem('api_tester_saved_tests', JSON.stringify(updated));
  };

  const addHeader = () => setHeaders([...headers, { key: '', value: '' }]);
  const updateHeader = (idx, field, val) => {
    const newHeaders = [...headers];
    newHeaders[idx][field] = val;
    setHeaders(newHeaders);
  };
  const removeHeader = (idx) => setHeaders(headers.filter((_, i) => i !== idx));

  const addAssertion = () => setAssertions([...assertions, { type: 'status', expected: '' }]);
  const updateAssertion = (idx, field, val) => {
    const newAssertions = [...assertions];
    newAssertions[idx][field] = val;
    setAssertions(newAssertions);
  };
  const removeAssertion = (idx) => setAssertions(assertions.filter((_, i) => i !== idx));

  const handleTest = async (e) => {
    e.preventDefault();
    if (!url) return;

    setLoading(true);
    setErrorMsg('');
    setResult(null);

    const validHeaders = headers.filter(h => h.key && h.value);
    const validAssertions = assertions.filter(a => a.type && a.expected);

    try {
      const response = await fetch('http://localhost:3001/api/manual-test', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ url, method, headers: validHeaders, body, assertions: validAssertions })
      });

      const data = await response.json();
      setResult(data);
    } catch (err) {
      setErrorMsg(err.message);
    } finally {
      setLoading(false);
    }
  };

  const exportDevReport = () => {
    if (!result) return;
    
    const report = `# API Test Failure Report\n
**Endpoint:** \`${result.request.method} ${result.request.url}\`
**Time:** ${new Date().toLocaleString()}
**Overall Status:** ${result.overallPass ? 'PASS ✅' : 'FAIL ❌'}

### 1. Intelligent Error Analysis
> **${result.resolutionSuggestion || 'No specific error identified.'}**

### 2. Request Details
**Headers:**
\`\`\`json
${JSON.stringify(result.request.headers, null, 2)}
\`\`\`
**Payload:**
\`\`\`json
${result.request.body || '{}'}
\`\`\`

### 3. Response Details
**Status:** ${result.response?.status} ${result.response?.statusText}
**Time:** ${result.response?.time}ms

**Response Body:**
\`\`\`json
${typeof result.response?.body === 'string' ? result.response?.body : JSON.stringify(result.response?.body, null, 2)}
\`\`\`

### 4. Failed Assertions
${result.assertions?.filter(a => !a.pass).map(a => `- **[${a.type}]**: Expected \`${a.expected}\`, but got \`${a.actualValue}\`\n  *Error: ${a.errorMsg}*`).join('\n') || '*None*'}

---
*Generated by API Tester Pro*
`;

    const blob = new Blob([report], { type: 'text/markdown' });
    const href = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = href;
    a.download = `API_Bug_Report_${Date.now()}.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
  };

  return (
    <div className="manual-test-container">
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '1rem' }}>
        <h2 style={{ margin: 0, fontSize: '1.2rem' }}>Comprehensive API Tester</h2>
        <button onClick={() => setShowSaved(!showSaved)} style={{ padding: '0.4rem 1rem', fontSize: '0.8rem', background: 'rgba(59, 130, 246, 0.2)', border: '1px solid var(--primary)' }}>
          {showSaved ? 'Close Saved Tests' : `Load Saved Tests (${savedTests.length})`}
        </button>
      </div>

      {showSaved && (
        <div className="glass-card" style={{ marginBottom: '1rem', background: 'rgba(0,0,0,0.3)' }}>
          <h3 style={{ marginBottom: '1rem', fontSize: '1rem', color: 'var(--primary)' }}>Saved Test Cases</h3>
          {savedTests.length === 0 ? <p style={{ color: 'var(--text-muted)', fontSize: '0.9rem' }}>No saved test cases yet.</p> : (
            <div style={{ display: 'grid', gap: '0.5rem' }}>
              {savedTests.map(tc => (
                <div key={tc.id} style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', background: 'rgba(255,255,255,0.05)', padding: '0.5rem 1rem', borderRadius: '4px' }}>
                  <div style={{ cursor: 'pointer', flex: 1 }} onClick={() => loadTestCase(tc)}>
                    <span className="badge badge-method" style={{ marginRight: '0.5rem' }}>{tc.method}</span>
                    <span style={{ fontSize: '0.9rem' }}>{tc.name}</span>
                  </div>
                  <button onClick={() => deleteTestCase(tc.id)} style={{ background: 'transparent', padding: '0.2rem', color: 'var(--error)', minWidth: 'auto' }}>
                    <Trash2 size={16} />
                  </button>
                </div>
              ))}
            </div>
          )}
        </div>
      )}

      <div className="glass-card" style={{ padding: '1.5rem' }}>
        <form onSubmit={handleTest}>
          <div className="input-group" style={{ marginBottom: '1.5rem' }}>
            <select 
              value={method} 
              onChange={e => setMethod(e.target.value)}
              style={{ background: 'rgba(15, 23, 42, 0.6)', color: 'white', border: '1px solid var(--border)', borderRadius: '8px', padding: '0 1rem', fontSize: '1rem', outline: 'none' }}
            >
              <option value="GET">GET</option>
              <option value="POST">POST</option>
              <option value="PUT">PUT</option>
              <option value="PATCH">PATCH</option>
              <option value="DELETE">DELETE</option>
            </select>
            <input
              type="url"
              placeholder="Enter API Endpoint URL (e.g., https://api.example.com/users)"
              value={url}
              onChange={(e) => setUrl(e.target.value)}
              required
              disabled={loading}
              style={{ flex: 1 }}
            />
            <button type="submit" disabled={loading} style={{ background: 'var(--success)' }}>
              {loading ? <Activity className="animate-spin" size={18} /> : <Play size={18} />}
              Send
            </button>
            <button type="button" onClick={saveTestCase} style={{ background: 'rgba(255,255,255,0.1)', border: '1px solid var(--border)' }} title="Save Test Case">
              <Save size={18} />
            </button>
          </div>

          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '2rem' }}>
            {/* Left Column: Headers & Body */}
            <div>
              <div style={{ marginBottom: '1.5rem' }}>
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '0.5rem' }}>
                  <h3 style={{ fontSize: '0.9rem', color: 'var(--text-muted)' }}>Headers</h3>
                  <button type="button" onClick={addHeader} style={{ background: 'transparent', color: 'var(--primary)', padding: 0, fontSize: '0.8rem', minWidth: 'auto' }}>
                    <Plus size={14} /> Add Header
                  </button>
                </div>
                {headers.map((header, idx) => (
                  <div key={idx} style={{ display: 'flex', gap: '0.5rem', marginBottom: '0.5rem' }}>
                    <input type="text" placeholder="Key (e.g. Authorization)" value={header.key} onChange={e => updateHeader(idx, 'key', e.target.value)} style={{ padding: '0.5rem', fontSize: '0.85rem' }} />
                    <input type="text" placeholder="Value" value={header.value} onChange={e => updateHeader(idx, 'value', e.target.value)} style={{ padding: '0.5rem', fontSize: '0.85rem' }} />
                    <button type="button" onClick={() => removeHeader(idx)} style={{ background: 'transparent', color: 'var(--error)', padding: '0 0.5rem', minWidth: 'auto' }}>
                      <XCircle size={16} />
                    </button>
                  </div>
                ))}
              </div>

              {['POST', 'PUT', 'PATCH'].includes(method) && (
                <div>
                  <h3 style={{ fontSize: '0.9rem', color: 'var(--text-muted)', marginBottom: '0.5rem' }}>Request Body (JSON)</h3>
                  <textarea 
                    value={body}
                    onChange={e => setBody(e.target.value)}
                    placeholder='{"key": "value"}'
                    spellCheck="false"
                    style={{ width: '100%', height: '120px', background: 'rgba(15, 23, 42, 0.6)', color: '#a78bfa', border: '1px solid var(--border)', borderRadius: '8px', padding: '0.8rem', fontFamily: 'monospace', fontSize: '0.85rem', resize: 'vertical', outline: 'none' }}
                  />
                </div>
              )}
            </div>

            {/* Right Column: Assertions */}
            <div>
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '0.5rem' }}>
                <h3 style={{ fontSize: '0.9rem', color: 'var(--text-muted)' }}>Test Assertions</h3>
                <button type="button" onClick={addAssertion} style={{ background: 'transparent', color: 'var(--primary)', padding: 0, fontSize: '0.8rem', minWidth: 'auto' }}>
                  <Plus size={14} /> Add Assertion
                </button>
              </div>
              <div style={{ background: 'rgba(0,0,0,0.2)', padding: '1rem', borderRadius: '8px', border: '1px solid var(--border)' }}>
                {assertions.length === 0 ? <p style={{ fontSize: '0.8rem', color: 'var(--text-muted)' }}>No assertions. Request will be executed without validation.</p> : null}
                {assertions.map((assertion, idx) => (
                  <div key={idx} style={{ display: 'flex', gap: '0.5rem', marginBottom: '0.5rem' }}>
                    <select 
                      value={assertion.type} 
                      onChange={e => updateAssertion(idx, 'type', e.target.value)}
                      style={{ background: 'rgba(15, 23, 42, 0.6)', color: 'white', border: '1px solid var(--border)', borderRadius: '4px', padding: '0.5rem', fontSize: '0.85rem', outline: 'none' }}
                    >
                      <option value="status">Expected Status</option>
                      <option value="responseTime">Max Response Time (ms)</option>
                      <option value="bodyContains">Body Contains</option>
                    </select>
                    <input type="text" placeholder="Expected Value" value={assertion.expected} onChange={e => updateAssertion(idx, 'expected', e.target.value)} style={{ padding: '0.5rem', fontSize: '0.85rem' }} />
                    <button type="button" onClick={() => removeAssertion(idx)} style={{ background: 'transparent', color: 'var(--error)', padding: '0 0.5rem', minWidth: 'auto' }}>
                      <XCircle size={16} />
                    </button>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </form>
      </div>

      {errorMsg && <div style={{ color: 'var(--error)', padding: '1rem', background: 'rgba(239, 68, 68, 0.1)', borderRadius: '8px', marginBottom: '1rem' }}>{errorMsg}</div>}

      {/* Results Dashboard */}
      {result && (
        <div className="glass-card result-dashboard" style={{ marginTop: '2rem', padding: '0' }}>
          {/* Header */}
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '1.5rem', borderBottom: '1px solid var(--border)', background: result.overallPass ? 'rgba(34, 197, 94, 0.05)' : 'rgba(239, 68, 68, 0.05)' }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: '1rem' }}>
              {result.overallPass ? <CheckCircle size={32} color="var(--success)" /> : <AlertTriangle size={32} color="var(--error)" />}
              <div>
                <h3 style={{ margin: 0, color: result.overallPass ? 'var(--success)' : 'var(--error)' }}>
                  {result.overallPass ? 'Test Passed' : 'Test Failed'}
                </h3>
                <p style={{ margin: 0, fontSize: '0.9rem', color: 'var(--text-muted)' }}>
                  {result.response?.status} {result.response?.statusText} • {result.response?.time}ms
                </p>
              </div>
            </div>
            
            {!result.overallPass && (
              <button onClick={exportDevReport} style={{ background: 'var(--primary)', padding: '0.5rem 1rem', fontSize: '0.9rem' }}>
                <Download size={16} /> Export Dev Report
              </button>
            )}
          </div>

          {/* Intelligent Error Analysis Panel */}
          {result.resolutionSuggestion && (
            <div style={{ margin: '1.5rem', padding: '1rem', background: result.overallPass ? 'rgba(34, 197, 94, 0.1)' : 'rgba(234, 179, 8, 0.1)', borderLeft: `4px solid ${result.overallPass ? 'var(--success)' : '#eab308'}`, borderRadius: '0 8px 8px 0' }}>
              <h4 style={{ margin: '0 0 0.5rem 0', display: 'flex', alignItems: 'center', gap: '0.5rem', color: result.overallPass ? 'var(--success)' : '#fde047' }}>
                <Activity size={18} /> Intelligent Error Analysis
              </h4>
              <p style={{ margin: 0, fontSize: '0.95rem', lineHeight: '1.5' }}>
                {result.resolutionSuggestion}
              </p>
            </div>
          )}

          {/* Assertions Results */}
          {result.assertions && result.assertions.length > 0 && (
            <div style={{ padding: '0 1.5rem 1.5rem' }}>
              <h4 style={{ margin: '0 0 1rem 0', color: 'var(--text-muted)' }}>Assertion Results</h4>
              <div style={{ display: 'grid', gap: '0.5rem' }}>
                {result.assertions.map((a, i) => (
                  <div key={i} style={{ display: 'flex', alignItems: 'center', gap: '1rem', padding: '0.8rem', background: 'rgba(0,0,0,0.2)', borderRadius: '4px', border: `1px solid ${a.pass ? 'rgba(34, 197, 94, 0.3)' : 'rgba(239, 68, 68, 0.3)'}` }}>
                    {a.pass ? <CheckCircle size={18} color="var(--success)" /> : <XCircle size={18} color="var(--error)" />}
                    <div style={{ flex: 1 }}>
                      <span style={{ fontSize: '0.9rem', fontWeight: 600, color: 'var(--text-main)' }}>{a.type}: </span>
                      <span style={{ fontSize: '0.9rem', color: 'var(--text-muted)' }}>Expected {a.expected}</span>
                    </div>
                    {!a.pass && <span style={{ fontSize: '0.8rem', color: 'var(--error)' }}>{a.errorMsg}</span>}
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* Response Body */}
          {result.response && (
            <div style={{ padding: '0 1.5rem 1.5rem' }}>
              <h4 style={{ margin: '0 0 0.5rem 0', color: 'var(--text-muted)' }}>Response Body</h4>
              <pre style={{ margin: 0, background: '#000', padding: '1rem', borderRadius: '8px', overflowX: 'auto', maxHeight: '400px', fontSize: '0.85rem', color: '#a78bfa', whiteSpace: 'pre-wrap' }}>
                {typeof result.response.body === 'string' ? result.response.body : JSON.stringify(result.response.body, null, 2)}
              </pre>
            </div>
          )}
        </div>
      )}
    </div>
  );
}
